const EMOJIS = [
["😃", "Grinning Face With Big Eyes"],
["😄", "Grinning Face With Smiling Eyes"],
["🙃", "Upside-Down Face"],
["🙂", "Slightly Smiling Face"],
["😀", "Grinning Face"],
["😆", "Grinning Squinting Face"],
["😇", "Smiling Face With Halo"],
["😁", "Beaming Face With Smiling Eyes"],
["😅", "Grinning Face With Sweat"],
["🫠", "Melting Face"],
["😊", "Smiling Face With Smiling Eyes"],
["😉", "Winking Face"],
["🤣", "Rolling on the Floor Laughing"],
["😂", "Face With Tears of Joy"],
["💟", "Heart Decoration"],
["❣️", "Heart Exclamation"],
["🩶", "Grey Heart"],
["💞", "Revolving Hearts"],
["💓", "Beating Heart"],
["🤎", "Brown Heart"],
["💘", "Heart With Arrow"],
["💝", "Heart With Ribbon"],
["💌", "Love Letter"],
["🧡", "Orange Heart"],
["💛", "Yellow Heart"],
["🩵", "Light Blue Heart"],
["💚", "Green Heart"],
["💗", "Growing Heart"],
["💕", "Two Hearts"],
["💜", "Purple Heart"],
["🖤", "Black Heart"],
["🤍", "White Heart"],
["❤️‍🔥", "Heart on fire"],
["🩷", "Pink Heart"],
["💙", "Blue Heart"],
["💖", "Sparkling Heart"],
["❤️‍🩹", "Mending heart"],
["💔", "Broken Heart"],
["❤️", "Red Heart"],
["🥸", "Disguised Face"],
["🤠", "Cowboy Hat Face"],
["🥳", "Partying Face"],
["🫪", "Distorted Face"],
["😦", "Frowning Face With Open Mouth"],
["🙁", "Slightly Frowning Face"],
["😧", "Anguished Face"],
["😯", "Hushed Face"],
["😓", "Downcast Face With Sweat"],
["😣", "Persevering Face"],
["😞", "Disappointed Face"],
["😕", "Confused Face"],
["😥", "Sad But Relieved Face"],
["😖", "Confounded Face"],
["😲", "Astonished Face"],
["😫", "Tired Face"],
["🥱", "Yawning Face"],
["☹️", "Frowning Face"],
["😟", "Worried Face"],
["🫤", "Face With Diagonal Mouth"],
["😰", "Anxious Face With Sweat"],
["😮", "Face With Open Mouth"],
["😱", "Face Screaming in Fear"],
["😩", "Weary Face"],
["😨", "Fearful Face"],
["😢", "Crying Face"],
["🥺", "Pleading Face", "beg"],
["🥹", "Face Holding Back Tears"],
["😳", "Flushed Face"],
["😭", "Loudly Crying Face", "sob"],
["😤", "Face With Steam From Nose"],
["👿", "Angry Face With Horns"],
["😠", "Angry Face"],
["🤬", "Face With Symbols On Mouth"],
["😡", "Pouting Face"],
["☠️", "Skull and Crossbones"],
["💀", "Skull"],
["😈", "Smiling Face With Horns", "devil"],
["🤧", "Sneezing Face"],
["🤒", "Face With Thermometer"],
["😷", "Face With Medical Mask"],
["🤕", "Face With Head-Bandage"],
["🤮", "Face Vomiting"],
["😵", "Dizzy Face"],
["🥴", "Woozy Face"],
["😵‍💫", "Face with spiral eyes"],
["🤢", "Nauseated Face"],
["🥵", "Hot Face"],
["🤯", "Exploding Head"],
["🥶", "Cold Face"],
["😾", "Pouting Cat"],
["😹", "Cat With Tears Of Joy"],
["😿", "Crying Cat"],
["🙀", "Weary Cat"],
["😽", "Kissing Cat"],
["😺", "Grinning Cat"],
["😸", "Grinning Cat With Smiling Eyes"],
["😼", "Cat With Wry Smile"],
["😻", "Smiling Cat With Heart-Eyes"],
["🤥", "Lying Face"],
["😶", "Face Without Mouth"],
["🤐", "Zipper-Mouth Face"],
["😐", "Neutral Face"],
["🫨", "Shaking Face"],
["😒", "Unamused Face"],
["😶‍🌫️", "Face in clouds"],
["😑", "Expressionless Face"],
["🙂‍↕️", "Head Shaking Vertically"],
["🤨", "Face With Raised Eyebrow"],
["😮‍💨", "Face exhaling"],
["🙂‍↔️", "Head Shaking Horizontally"],
["😏", "Smirking Face"],
["🫥", "Dotted Line Face"],
["😬", "Grimacing Face"],
["🙄", "Face With Rolling Eyes"],
["😛", "Face With Tongue"],
["😝", "Squinting Face With Tongue"],
["😋", "Face Savoring Food"],
["🤑", "Money-Mouth Face"],
["😜", "Winking Face With Tongue"],
["🤪", "Zany Face"],
["🙉", "Hear-no-evil Monkey"],
["🙊", "Speak-No-Evil Monkey"],
["🙈", "See-No-Evil Monkey"],
["🫩", "Face with Bags under Eyes"],
["😪", "Sleepy Face"],
["🤤", "Drooling Face"],
["😴", "Sleeping Face"],
["😔", "Pensive Face"],
["😌", "Relieved Face"],
["🫢", "Face With Open Eyes And Hand Over Mouth"],
["🤫", "Shushing Face"],
["🤭", "Face With Hand Over Mouth"],
["🤗", "Hugging Face"],
["🤔", "Thinking Face"],
["🫣", "Face With Peeking Eye"],
["🫡", "Saluting Face"],
["🫯", "Fight Cloud"],
["🗯️", "Right Anger Bubble"],
["🗨️", "Left Speech Bubble"],
["💢", "Anger Symbol"],
["🕳️", "Hole"],
["👁️‍🗨️", "Eye In Speech Bubble"],
["💯", "Hundred Points"],
["💭", "Thought Balloon"],
["💨", "Dashing Away"],
["💤", "Zzz"],
["💬", "Speech Balloon"],
["💦", "Sweat Droplets"],
["💋", "Kiss Mark"],
["💫", "Dizzy"],
["💥", "Collision"],
["😙", "Kissing Face With Smiling Eyes"],
["😚", "Kissing Face With Closed Eyes"],
["😗", "Kissing Face"],
["🥲", "Smiling Face With Tear"],
["☺️", "Smiling Face"],
["🤩", "Star-Struck"],
["😍", "Smiling Face With Heart-Eyes"],
["😘", "Face Blowing a Kiss"],
["🥰", "Smiling Face With Hearts"],
["👺", "Goblin", "mask"],
["💩", "Pile of Poo", "shit"],
["👾", "Alien Monster"],
["👽", "Alien"],
["🤡", "Clown Face"],
["🤖", "Robot"],
["👹", "Ogre"],
["👻", "Ghost"],
["🧐", "Face With Monocle"],
["🤓", "Nerd Face"],
["😎", "Smiling Face With Sunglasses"],
["🧘‍♂️", "Man In Lotus Position"],
["🛀", "Person Taking Bath"],
["🧘", "Person In Lotus Position"],
["🛌", "Person in Bed"],
["🧘‍♀️", "Woman In Lotus Position"],
["🧑‍🩰", "Ballet Dancer"],
["🧑‍🦯‍➡️", "Person With White Cane Facing Right"],
["👩‍🦽‍➡️", "Woman In Manual Wheelchair Facing Right"],
["👩‍🦼‍➡️", "Woman In Motorized Wheelchair Facing Right"],
["🚶‍♂️‍➡️", "Man Walking Facing Right"],
["👩‍🦯‍➡️", "Woman With White Cane Facing Right"],
["🧑‍🦼‍➡️", "Person In Motorized Wheelchair Facing Right"],
["👨‍🦽‍➡️", "Man In Manual Wheelchair Facing Right"],
["🧑‍🦽‍➡️", "Person In Manual Wheelchair Facing Right"],
["🧎‍➡️", "Person Kneeling Facing Right"],
["🧎‍♂️‍➡️", "Man Kneeling Facing Right"],
["👨‍🦼‍➡️", "Man In Motorized Wheelchair Facing Right"],
["🏃‍♀️‍➡️", "Woman Running Facing Right"],
["🏃‍♂️‍➡️", "Man Running Facing Right"],
["🚶‍♀️‍➡️", "Woman Walking Facing Right"],
["🧑‍🦼", "Person In Motorized Wheelchair"],
["👨‍🦯‍➡️", "Man With White Cane Facing Right"],
["🧑‍🦽", "Person In Manual Wheelchair"],
["👩‍🦼", "Woman In Motorized Wheelchair"],
["👨‍🦼", "Man In Motorized Wheelchair"],
["👩‍🦽", "Woman In Manual Wheelchair"],
["🧎‍♀️‍➡️", "Woman Kneeling Facing Right"],
["🚶‍➡️", "Person Walking Facing Right"],
["🧑‍🦯", "Person With White Cane"],
["💇‍♂️", "Man Getting Haircut"],
["🏃‍➡️", "Person Running Facing Right"],
["💇", "Person Getting Haircut"],
["🧖", "Person In Steamy Room"],
["👩‍🦯", "Woman With White Cane"],
["👨‍🦽", "Man In Manual Wheelchair"],
["👯‍♂️", "Men With Bunny Ears"],
["🧗‍♀️", "Woman Climbing"],
["🧗‍♂️", "Man Climbing"],
["🧖‍♂️", "Man In Steamy Room"],
["🧎", "Person Kneeling"],
["🧎‍♂️", "Man Kneeling"],
["💆", "Person Getting Massage"],
["💇‍♀️", "Woman Getting Haircut"],
["👨‍🦯", "Man With White Cane"],
["🧍", "Person Standing"],
["🧍‍♂️", "Man Standing"],
["👯", "People With Bunny Ears"],
["🧗", "Person Climbing"],
["🕴️", "Person In Suit Levitating"],
["🧍‍♀️", "Woman Standing"],
["💆‍♂️", "Man Getting Massage"],
["🚶", "Person Walking"],
["🚶‍♀️", "Woman Walking"],
["🚶‍♂️", "Man Walking"],
["👯‍♀️", "Women With Bunny Ears"],
["🏃‍♂️", "Man Running"],
["🧖‍♀️", "Woman In Steamy Room"],
["🏃‍♀️", "Woman Running"],
["🧎‍♀️", "Woman Kneeling"],
["💆‍♀️", "Woman Getting Massage"],
["🏃", "Person Running"],
["🕺", "Man Dancing"],
["💃", "Woman Dancing"],
["🤏", "Pinching Hand"],
["🤟", "Love-You Gesture"],
["🤌", "Pinched Fingers"],
["🤙", "Call Me Hand"],
["👌", "OK Hand"],
["🫰", "Hand With Index Finger And Thumb Crossed"],
["🤞", "Crossed Fingers"],
["✌️", "Victory Hand"],
["🤘", "Sign of the Horns"],
["🤛", "Left-Facing Fist"],
["🤜", "Right-Facing Fist"],
["✊", "Raised Fist"],
["👎", "Thumbs Down"],
["👊", "Oncoming Fist"],
["👍", "Thumbs Up"],
["🤳", "Selfie"],
["💅", "Nail Polish"],
["✍️", "Writing Hand"],
["🦻", "Ear With Hearing Aid"],
["🦿", "Mechanical Leg"],
["🫁", "Lungs"],
["👃", "Nose"],
["👂", "Ear"],
["🦷", "Tooth"],
["🦵", "Leg"],
["🦶", "Foot"],
["🦴", "Bone"],
["👄", "Mouth"],
["🦾", "Mechanical Arm"],
["🫦", "Biting Lip"],
["👁️", "Eye"],
["🫀", "Anatomical Heart"],
["🧠", "Brain"],
["👅", "Tongue"],
["💪", "Flexed Biceps"],
["👀", "Eyes"],
["👨‍🦰", "Man: Red Hair"],
["🧑‍🦳", "Person: White Hair"],
["🧑‍🦱", "Person: Curly Hair"],
["👨‍🦱", "Man: Curly Hair"],
["👨‍🦳", "Man: White Hair"],
["🧑‍🦲", "Person: Bald"],
["👱‍♂️", "Man: Blond Hair"],
["👱", "Person: Blond Hair"],
["👩‍🦲", "Woman: Bald"],
["👨‍🦲", "Man: Bald"],
["👩‍🦱", "Woman: Curly Hair"],
["🧑‍🦰", "Person: Red Hair"],
["🧓", "Older Person"],
["🧔‍♂️", "Man: Beard"],
["🧔‍♀️", "Woman: Beard"],
["👩‍🦳", "Woman: White Hair"],
["🧔", "Person: Beard"],
["👩‍🦰", "Woman: Red Hair"],
["👱‍♀️", "Woman: Blond Hair"],
["🧒", "Child"],
["👴", "Old Man"],
["👵", "Old Woman"],
["🧑", "Person"],
["👦", "Boy"],
["👧", "Girl"],
["👶", "Baby"],
["👨", "Man"],
["👩", "Woman"],
["👐", "Open Hands"],
["🤲", "Palms Up Together"],
["👏", "Clapping Hands"],
["🤝", "Handshake"],
["🫶", "Heart Hands"],
["🙌", "Raising Hands"],
["🙏", "Folded Hands"],
["🙎‍♂️", "Man Pouting"],
["🙎", "Person Pouting"],
["🙍‍♂️", "Man Frowning"],
["🙍", "Person Frowning"],
["🙍‍♀️", "Woman Frowning"],
["🙎‍♀️", "Woman Pouting"],
["🧏‍♂️", "Deaf Man"],
["💁", "Person Tipping Hand"],
["🙆", "Person Gesturing OK"],
["🧏‍♀️", "Deaf Woman"],
["🧏", "Deaf Person"],
["🙋", "Person Raising Hand"],
["🙅", "Person Gesturing NO"],
["💁‍♂️", "Man Tipping Hand"],
["🙇", "Person Bowing"],
["🙅‍♂️", "Man Gesturing NO"],
["💁‍♀️", "Woman Tipping Hand"],
["🙋‍♂️", "Man Raising Hand"],
["🙆‍♂️", "Man Gesturing OK"],
["🙋‍♀️", "Woman Raising Hand"],
["🤷", "Person Shrugging"],
["🙇‍♂️", "Man Bowing"],
["🙅‍♀️", "Woman Gesturing NO"],
["🤷‍♂️", "Man Shrugging"],
["🙆‍♀️", "Woman Gesturing OK"],
["🤦‍♂️", "Man Facepalming"],
["🤦", "Person Facepalming"],
["🤦‍♀️", "Woman Facepalming"],
["🤷‍♀️", "Woman Shrugging"],
["🙇‍♀️", "Woman Bowing"],
["💂‍♀️", "Woman Guard"],
["🤵‍♀️", "Woman In Tuxedo"],
["👩‍🚒", "Woman Firefighter"],
["🧑‍🏭", "Factory Worker"],
["👳‍♀️", "Woman Wearing Turban"],
["👩‍🏭", "Woman Factory Worker"],
["🧑‍🍼", "Person Feeding Baby"],
["👨‍🚒", "Man Firefighter"],
["👩‍✈️", "️Woman Pilot"],
["👩‍🔧", "Woman Mechanic"],
["👷‍♀️", "Woman Construction Worker"],
["🧑‍🚒", "Firefighter"],
["👳‍♂️", "Man Wearing Turban"],
["👨‍🍼", "Man Feeding Baby"],
["🤵‍♂️", "Man In Tuxedo"],
["🧑‍✈️", "Pilot"],
["👩‍🚀", "Woman Astronaut"],
["👰‍♂️", "Man With Veil"],
["🧑‍🔬", "Scientist"],
["👲", "Person With Skullcap"],
["💂‍♂️", "Man Guard"],
["🧑‍⚕️", "Health Worker"],
["👨‍✈️", "️Man Pilot"],
["🧑‍🔧", "Mechanic"],
["👳", "Person Wearing Turban"],
["🧑‍⚖️", "Judge"],
["👩‍🍼", "Woman Feeding Baby"],
["🧑‍🚀", "Astronaut"],
["👨‍🎓", "Man Student"],
["👰‍♀️", "Woman With Veil"],
["👨‍🏫", "Man Teacher"],
["🫄", "Pregnant Person"],
["👨‍🚀", "Man Astronaut"],
["👮‍♀️", "Woman Police Officer"],
["🤱", "Breast-Feeding"],
["👷‍♂️", "Man Construction Worker"],
["👨‍🎨", "Man Artist"],
["👩‍🎓", "Woman Student"],
["🤵", "Person In Tuxedo"],
["👩‍🎨", "Woman Artist"],
["👷", "Construction Worker"],
["👩‍🍳", "Woman Cook"],
["🧕", "Woman With Headscarf"],
["👩‍🌾", "Woman Farmer"],
["🧑‍💼", "Office Worker"],
["🫅", "Person With Crown"],
["👨‍⚕️", "️Man Health Worker"],
["👨‍⚖️", "️Man Judge"],
["🧑‍🌾", "Farmer"],
["💂", "Guard"],
["🧑‍🍳", "Cook"],
["🕵️‍♀️", "Woman Detective"],
["🧑‍🏫", "Teacher"],
["👨‍🔬", "Man Scientist"],
["👩‍⚖️", "️Woman Judge"],
["👨‍🔧", "Man Mechanic"],
["👨‍🌾", "Man Farmer"],
["👨‍🎤", "Man Singer"],
["🧑‍🎨", "Artist"],
["👩‍🎤", "Woman Singer"],
["🧑‍🎤", "Singer"],
["🫃", "Pregnant Man"],
["👰", "Person With Veil"],
["👩‍🔬", "Woman Scientist"],
["👩‍💼", "Woman Office Worker"],
["🧑‍🎓", "Student"],
["👮‍♂️", "Man Police Officer"],
["👩‍🏫", "Woman Teacher"],
["🤴", "Prince"],
["👨‍🏭", "Man Factory Worker"],
["👩‍⚕️", "️Woman Health Worker"],
["🤰", "Pregnant Woman"],
["👨‍🍳", "Man Cook"],
["👨‍💼", "Man Office Worker"],
["👮", "Police Officer"],
["🧑‍💻", "Technologist"],
["🕵️‍♂️", "Man Detective"],
["👸", "Princess"],
["🕵️", "Detective"],
["👩‍💻", "Woman Technologist"],
["🥷", "Ninja"],
["👨‍💻", "Man Technologist"],
["👩‍👩‍👦", "Family: Woman, Woman, Boy"],
["👨‍👨‍👧", "Family: Man, Man, Girl"],
["👩‍👩‍👦‍👦", "Family: Woman, Woman, Boy, Boy"],
["👩‍👦‍👦", "Family: Woman, Boy, Boy"],
["👩‍👩‍👧", "Family: Woman, Woman, Girl"],
["👩‍👩‍👧‍👧", "Family: Woman, Woman, Girl, Girl"],
["👨‍👦‍👦", "Family: Man, Boy, Boy"],
["👨‍👨‍👧‍👧", "Family: Man, Man, Girl, Girl"],
["👨‍👩‍👦‍👦", "Family: Man, Woman, Boy, Boy"],
["👨‍👧", "Family: Man, Girl"],
["👨‍👨‍👧‍👦", "Family: Man, Man, Girl, Boy"],
["👨‍👨‍👦‍👦", "Family: Man, Man, Boy, Boy"],
["👨‍👩‍👧‍👧", "Family: Man, Woman, Girl, Girl"],
["👩‍👧‍👧", "Family: Woman, Girl, Girl"],
["👨‍👨‍👦", "Family: Man, Man, Boy"],
["👨‍👧‍👦", "Family: Man, Girl, Boy"],
["👬", "Men Holding Hands"],
["👨‍👩‍👦", "Family: Man, Woman, Boy"],
["👨‍❤️‍👨", "Couple With Heart: Man, Man"],
["👨‍👩‍👧", "Family: Man, Woman, Girl"],
["👨‍👧‍👧", "Family: Man, Girl, Girl"],
["👨‍❤️‍💋‍👨", "Kiss: Man, Man"],
["👩‍👩‍👧‍👦", "Family: Woman, Woman, Girl, Boy"],
["👩‍❤️‍💋‍👩", "Kiss: Woman, Woman"],
["👨‍👦", "Family: Man, Boy"],
["👭", "Women Holding Hands"],
["👨‍👩‍👧‍👦", "Family: Man, Woman, Girl, Boy"],
["👩‍❤️‍💋‍👨", "Kiss: Woman, Man"],
["💏", "Kiss"],
["👩‍❤️‍👩", "Couple With Heart: Woman, Woman"],
["🧑‍🤝‍🧑", "People Holding Hands"],
["👫", "Woman And Man Holding Hands"],
["👩‍👧‍👦", "Family: Woman, Girl, Boy"],
["👩‍❤️‍👨", "Couple With Heart: Woman, Man"],
["💑", "Couple With Heart"],
["👩‍👦", "Family: Woman, Boy"],
["👩‍👧", "Family: Woman, Girl"],
["🫈", "Hairy Creature"],
["🧜", "Merperson"],
["🦹‍♂️", "Man Supervillain"],
["🦹‍♀️", "Woman Supervillain"],
["🧝‍♂️", "Man Elf"],
["🧛‍♀️", "Woman Vampire"],
["🧛‍♂️", "Man Vampire"],
["🦹", "Supervillain"],
["🧞‍♀️", "Woman Genie"],
["🧝‍♀️", "Woman Elf"],
["🧚‍♂️", "Man Fairy"],
["🧝", "Elf"],
["🦸‍♀️", "Woman Superhero"],
["🧑‍🎄", "Mx Claus"],
["🧞", "Genie"],
["🧞‍♂️", "Man Genie"],
["🧜‍♂️", "Merman"],
["🧟‍♀️", "Woman Zombie"],
["🦸", "Superhero"],
["🦸‍♂️", "Man Superhero"],
["🧙‍♀️", "Woman Mage"],
["🤶", "Mrs. Claus"],
["🧛", "Vampire"],
["🧜‍♀️", "Mermaid"],
["🧟‍♂️", "Man Zombie"],
["🧚‍♀️", "Woman Fairy"],
["🧚", "Fairy"],
["🧟", "Zombie"],
["🧙", "Mage"],
["🧙‍♂️", "Man Mage"],
["🧌", "Troll"],
["👼", "Baby Angel"],
["🎅", "Santa Claus"],
["🫷", "Leftwards Pushing Hand"],
["🫲", "Leftwards Hand"],
["🫸", "Rightwards Pushing Hand"],
["🫳", "Palm Down Hand"],
["🖐️", "Hand With Fingers Splayed"],
["🤚", "Raised Back of Hand"],
["🫱", "Rightwards Hand"],
["🫴", "Palm Up Hand"],
["✋", "Raised Hand"],
["🖖", "Vulcan Salute"],
["👋", "Waving Hand"],
["☝️", "Index Pointing Up"],
["👈", "Backhand Index Pointing Left"],
["👇", "Backhand Index Pointing Down"],
["🖕", "Middle Finger"],
["👆", "Backhand Index Pointing Up"],
["👉", "Backhand Index Pointing Right"],
["🫵", "Index Pointing At The Viewer"],
["🫆", "Fingerprint"],
["🧑‍🧒‍🧒", "Family: Adult, Child, Child"],
["🧑‍🧑‍🧒‍🧒", "Family: Adult, Adult, Child, Child"],
["🧑‍🧑‍🧒", "Family: Adult, Adult, Child"],
["🧑‍🧒", "Family: Adult, Child"],
["👤", "Bust in Silhouette"],
["👣", "Footprints"],
["👪", "Family"],
["👥", "Busts in Silhouette"],
["🫂", "People Hugging"],
["🗣️", "Speaking Head"],
["🤽‍♀️", "Woman Playing Water Polo"],
["🚵‍♀️", "Woman Mountain Biking"],
["🤽‍♂️", "Man Playing Water Polo"],
["⛹️", "Person Bouncing Ball"],
["🚵", "Person Mountain Biking"],
["🚣‍♂️", "Man Rowing Boat"],
["🤽", "Person Playing Water Polo"],
["🚵‍♂️", "Man Mountain Biking"],
["⛹️‍♀️", "Woman Bouncing Ball"],
["🤾‍♀️", "Woman Playing Handball"],
["🏌️‍♀️", "Woman Golfing"],
["🤾‍♂️", "Man Playing Handball"],
["⛹️‍♂️", "Man Bouncing Ball"],
["🏌️‍♂️", "Man Golfing"],
["🚣‍♀️", "Woman Rowing Boat"],
["🚴‍♂️", "Man Biking"],
["🤹‍♀️", "Woman Juggling"],
["🤼‍♀️", "Women Wrestling"],
["🤾", "Person Playing Handball"],
["🤸‍♂️", "Man Cartwheeling"],
["🏊‍♂️", "Man Swimming"],
["🏌️", "Person Golfing"],
["🚴‍♀️", "Woman Biking"],
["🏄‍♀️", "Woman Surfing"],
["🚴", "Person Biking"],
["🤹‍♂️", "Man Juggling"],
["🏊‍♀️", "Woman Swimming"],
["🤹", "Person Juggling"],
["🤸", "Person Cartwheeling"],
["🏄", "Person Surfing"],
["🏂", "Snowboarder"],
["🚣", "Person Rowing Boat"],
["🤼‍♂️", "Men Wrestling"],
["🤼", "People Wrestling"],
["🏊", "Person Swimming"],
["🏇", "Horse Racing"],
["🏋️", "Person Lifting Weights"],
["🏄‍♂️", "Man Surfing"],
["🏋️‍♀️", "Woman Lifting Weights"],
["🤸‍♀️", "Woman Cartwheeling"],
["🤺", "Person Fencing"],
["⛷️", "Skier"],
["🏋️‍♂️", "Man Lifting Weights"],
["🦎", "Lizard"],
["🐊", "Crocodile"],
["🐲", "Dragon Face"],
["🐢", "Turtle"],
["🦕", "Sauropod"],
["🐍", "Snake"],
["🦖", "T-Rex"],
["🐉", "Dragon"],
["🫍", "Orca"],
["🪸", "Coral"],
["🦪", "Oyster"],
["🦐", "Shrimp"],
["🦑", "Squid"],
["🦞", "Lobster"],
["🐡", "Blowfish"],
["🐬", "Dolphin"],
["🦀", "Crab"],
["🦭", "Seal"],
["🐠", "Tropical Fish"],
["🐚", "Spiral Shell"],
["🪼", "Jellyfish"],
["🦈", "Shark"],
["🐳", "Spouting Whale"],
["🐙", "Octopus"],
["🐋", "Whale"],
["🐟", "Fish"],
["🦡", "Badger"],
["🦮", "Guide Dog"],
["🦬", "Bison"],
["🐫", "Two-Hump Camel"],
["🐩", "Poodle"],
["🐃", "Water Buffalo"],
["🐕‍🦺", "Service Dog"],
["🦙", "Llama"],
["🐏", "Ram"],
["🦨", "Skunk"],
["🦫", "Beaver"],
["🫎", "Moose"],
["🐨", "Koala"],
["🐗", "Boar"],
["🦝", "Raccoon"],
["🐹", "Hamster"],
["🐻‍❄️", "Polar Bear"],
["🦏", "Rhinoceros"],
["🦣", "Mammoth"],
["🦓", "Zebra"],
["🐂", "Ox"],
["🫏", "Donkey"],
["🦥", "Sloth"],
["🦛", "Hippopotamus"],
["🦘", "Kangaroo"],
["🐁", "Mouse"],
["🐽", "Pig Nose"],
["🦧", "Orangutan"],
["🐭", "Mouse Face"],
["🦦", "Otter"],
["🐯", "Tiger Face"],
["🦔", "Hedgehog"],
["🐖", "Pig"],
["🐪", "Camel"],
["🐴", "Horse Face"],
["🐿️", "Chipmunk"],
["🐵", "Monkey Face"],
["🦒", "Giraffe"],
["🐅", "Tiger"],
["🐀", "Rat"],
["🐷", "Pig Face"],
["🐆", "Leopard"],
["🐑", "Ewe"],
["🐮", "Cow Face"],
["🐰", "Rabbit Face"],
["🦍", "Gorilla"],
["🐄", "Cow"],
["🦌", "Deer"],
["🐐", "Goat"],
["🐈‍⬛", "Black Cat"],
["🐼", "Panda"],
["🐎", "Horse"],
["🐒", "Monkey"],
["🐇", "Rabbit"],
["🐱", "Cat Face"],
["🦊", "Fox"],
["🐻", "Bear"],
["🐶", "Dog Face"],
["🐺", "Wolf"],
["🐘", "Elephant"],
["🦁", "Lion"],
["🐕", "Dog"],
["🐾", "Paw Prints"],
["🦄", "Unicorn"],
["🦇", "Bat"],
["🐈", "Cat"],
["🐸", "Frog"],
["🪾", "Leafless Tree"],
["🪹", "Empty Nest"],
["🪺", "Nest With Eggs"],
["🪴", "Potted Plant"],
["🌾", "Sheaf of Rice"],
["🌵", "Cactus"],
["🍄", "Mushroom"],
["☘️", "Shamrock"],
["🍁", "Maple Leaf"],
["🌴", "Palm Tree"],
["🌲", "Evergreen Tree"],
["🌳", "Deciduous Tree"],
["🍃", "Leaf Fluttering in Wind"],
["🌱", "Seedling"],
["🍂", "Fallen Leaf"],
["🍀", "Four Leaf Clover"],
["🌿", "Herb"],
["🏵️", "Rosette"],
["💮", "White Flower"],
["🪻", "Hyacinth"],
["🪷", "Lotus"],
["🌻", "Sunflower"],
["🌷", "Tulip"],
["💐", "Bouquet"],
["🌺", "Hibiscus"],
["🌼", "Blossom"],
["🌸", "Cherry Blossom"],
["🌹", "Rose"],
["🥀", "Wilted Flower", "withered rose"],
["🪳", "Cockroach"],
["🦂", "Scorpion"],
["🪰", "Fly"],
["🦠", "Microbe"],
["🐌", "Snail"],
["🦟", "Mosquito"],
["🪲", "Beetle"],
["🪱", "Worm"],
["🦗", "Cricket"],
["🐜", "Ant"],
["🐞", "Lady Beetle"],
["🐛", "Bug"],
["🕸️", "Spider Web"],
["🐝", "Honeybee"],
["🕷️", "Spider"],
["🦋", "Butterfly"],
["🦤", "Dodo"],
["🪿", "Goose"],
["🪶", "Feather"],
["🐤", "Baby Chick"],
["🦚", "Peacock"],
["🐓", "Rooster"],
["🦜", "Parrot"],
["🦩", "Flamingo"],
["🐦‍🔥", "Phoenix"],
["🐣", "Hatching Chick"],
["🦢", "Swan"],
["🐥", "Front-Facing Baby Chick"],
["🐔", "Chicken"],
["🦉", "Owl"],
["🦆", "Duck"],
["🪽", "Wing"],
["🐦‍⬛", "Black Bird"],
["🐦", "Bird"],
["🐧", "Penguin"],
["🦃", "Turkey"],
["🕊️", "Dove"],
["🦅", "Eagle"],
["🍧", "Shaved Ice"],
["🍮", "Custard"],
["🍦", "Soft Ice Cream"],
["🍩", "Doughnut"],
["🍨", "Ice Cream"],
["🧁", "Cupcake"],
["🥧", "Pie"],
["🍯", "Honey Pot"],
["🍰", "Shortcake"],
["🍭", "Lollipop"],
["🍫", "Chocolate Bar"],
["🍬", "Candy"],
["🍪", "Cookie"],
["🎂", "Birthday Cake"],
["🍐", "Pear"],
["🍋‍🟩", "Lime"],
["🫒", "Olive"],
["🥝", "Kiwi Fruit"],
["🍍", "Pineapple"],
["🍈", "Melon"],
["🍅", "Tomato"],
["🍋", "Lemon"],
["🍇", "Grapes"],
["🥥", "Coconut"],
["🥭", "Mango"],
["🍉", "Watermelon"],
["🫐", "Blueberries"],
["🍏", "Green Apple"],
["🍊", "Tangerine"],
["🍌", "Banana"],
["🍒", "Cherries"],
["🍎", "Red Apple"],
["🍓", "Strawberry"],
["🍑", "Peach"],
["🫙", "Jar"],
["🥢", "Chopsticks"],
["🏺", "Amphora"],
["🍴", "Fork and Knife"],
["🍽️", "Fork and Knife With Plate"],
["🔪", "Kitchen Knife"],
["🥄", "Spoon"],
["🍶", "Sake"],
["🧉", "Mate"],
["🫖", "Teapot"],
["🫗", "Pouring Liquid"],
["🍵", "Teacup Without Handle"],
["🧃", "Beverage Box"],
["🥃", "Tumbler Glass"],
["🍼", "Baby Bottle"],
["🍸", "Cocktail Glass"],
["🥛", "Glass of Milk"],
["🍻", "Clinking Beer Mugs"],
["🍹", "Tropical Drink"],
["🧊", "Ice"],
["🧋", "Bubble Tea"],
["🥤", "Cup With Straw"],
["🍷", "Wine Glass"],
["🍺", "Beer Mug"],
["🍾", "Bottle With Popping Cork"],
["☕", "Hot Beverage"],
["🥂", "Clinking Glasses"],
["🫜", "Root Vegetable"],
["🍄‍🟫", "Brown Mushroom"],
["🧄", "Garlic"],
["🫑", "Bell Pepper"],
["🧅", "Onion"],
["🫛", "Pea Pod"],
["🫘", "Beans"],
["🥬", "Leafy Green"],
["🫚", "Ginger Root"],
["🌰", "Chestnut"],
["🥦", "Broccoli"],
["🌽", "Ear of Corn"],
["🥜", "Peanuts"],
["🥔", "Potato"],
["🥒", "Cucumber"],
["🥑", "Avocado"],
["🥕", "Carrot"],
["🌶️", "Hot Pepper"],
["🍆", "Eggplant"],
["🫓", "Flatbread"],
["🫔", "Tamale"],
["🫕", "Fondue"],
["🧆", "Falafel"],
["🥯", "Bagel"],
["🥫", "Canned Food"],
["🌯", "Burrito"],
["🥙", "Stuffed Flatbread"],
["🧂", "Salt"],
["🧈", "Butter"],
["🥨", "Pretzel"],
["🧇", "Waffle"],
["🥓", "Bacon"],
["🥪", "Sandwich"],
["🥘", "Shallow Pan Of Food"],
["🥣", "Bowl With Spoon"],
["🥖", "Baguette Bread"],
["🥞", "Pancakes"],
["🥗", "Green Salad"],
["🍲", "Pot of Food"],
["🌭", "Hot Dog"],
["🧀", "Cheese Wedge"],
["🥩", "Cut Of Meat"],
["🥐", "Croissant"],
["🍖", "Meat on Bone"],
["🍗", "Poultry Leg"],
["🌮", "Taco"],
["🍳", "Cooking"],
["🍟", "French Fries"],
["🍞", "Bread"],
["🍿", "Popcorn"],
["🥚", "Egg"],
["🍕", "Pizza"],
["🍔", "Hamburger"],
["🥡", "Takeout Box"],
["🍘", "Rice Cracker"],
["🥠", "Fortune Cookie"],
["🍙", "Rice Ball"],
["🍤", "Fried Shrimp"],
["🍢", "Oden"],
["🍱", "Bento Box"],
["🍠", "Roasted Sweet Potato"],
["🍚", "Cooked Rice"],
["🍥", "Fish Cake With Swirl"],
["🥮", "Moon Cake"],
["🍛", "Curry Rice"],
["🍜", "Steaming Bowl"],
["🥟", "Dumpling"],
["🍝", "Spaghetti"],
["🍣", "Sushi"],
["🍡", "Dango"],
["🌥️", "Sun Behind Large Cloud"],
["⛱️", "Umbrella on Ground"],
["🌂", "Closed Umbrella"],
["🌩️", "Cloud With Lightning"],
["🌦️", "Sun Behind Rain Cloud"],
["🌛", "First Quarter Moon Face"],
["🌫️", "Fog"],
["⛅", "Sun Behind Cloud"],
["☂️", "Umbrella"],
["⛈️", "Cloud With Lightning and Rain"],
["🌜", "Last Quarter Moon Face"],
["🌡️", "Thermometer"],
["🌤️", "Sun Behind Small Cloud"],
["🌨️", "Cloud With Snow"],
["☔", "Umbrella With Rain Drops"],
["🌪️", "Tornado"],
["🌬️", "Wind Face"],
["🌝", "Full Moon Face"],
["🌠", "Shooting Star"],
["🌧️", "Cloud With Rain"],
["🪐", "Ringed Planet"],
["🌚", "New Moon Face"],
["☄️", "Comet"],
["🌗", "Last Quarter Moon"],
["☁️", "Cloud"],
["🌞", "Sun With Face"],
["⛄", "Snowman Without Snow"],
["💧", "Droplet"],
["⚡", "High Voltage"],
["🌈", "Rainbow"],
["🌌", "Milky Way"],
["🌓", "First Quarter Moon"],
["🌕", "Full Moon"],
["🌊", "Water Wave"],
["🌙", "Crescent Moon"],
["🌀", "Cyclone"],
["☃️", "Snowman"],
["🌖", "Waning Gibbous Moon"],
["🌘", "Waning Crescent Moon"],
["🌔", "Waxing Gibbous Moon"],
["🌑", "New Moon"],
["☀️", "Sun"],
["🌟", "Glowing Star"],
["🌒", "Waxing Crescent Moon"],
["⭐", "Star"],
["❄️", "Snowflake"],
["🔥", "Fire"],
["🕍", "Synagogue"],
["⛩️", "Shinto Shrine"],
["🛕", "Hindu Temple"],
["🕌", "Mosque"],
["🕋", "Kaaba"],
["⛪", "Church"],
["🕢", "Seven-Thirty"],
["🕟", "Four-Thirty"],
["🕣", "Eight-Thirty"],
["🕤", "Nine-Thirty"],
["🕠", "Five-Thirty"],
["🕡", "Six-Thirty"],
["🕥", "Ten-Thirty"],
["🕞", "Three-Thirty"],
["🕚", "Eleven O’clock"],
["🕦", "Eleven-Thirty"],
["🕖", "Seven O’clock"],
["🕘", "Nine O’clock"],
["🕜", "One-Thirty"],
["🕧", "Twelve-Thirty"],
["🕗", "Eight O’clock"],
["🕕", "Six O’clock"],
["🕙", "Ten O’clock"],
["🕔", "Five O’clock"],
["🕓", "Four O’clock"],
["🕝", "Two-Thirty"],
["🕐", "One O’clock"],
["🕒", "Three O’clock"],
["🕑", "Two O’clock"],
["⏲️", "Timer Clock"],
["⏱️", "Stopwatch"],
["🕰️", "Mantelpiece Clock"],
["🕛", "Twelve O’clock"],
["⌚", "Watch"],
["⏰", "Alarm Clock"],
["⌛", "Hourglass Done"],
["⏳", "Hourglass Not Done"],
["🗾", "Map of Japan"],
["🌏", "Globe Showing Asia-Australia"],
["🧭", "Compass"],
["🌍", "Globe Showing Europe-Africa"],
["🗺️", "World Map"],
["🌐", "Globe With Meridians"],
["🌎", "Globe Showing Americas"],
["🏣", "Japanese Post Office"],
["🏤", "Post Office"],
["🛖", "Hut"],
["🏬", "Department Store"],
["🏪", "Convenience Store"],
["🏩", "Love Hotel"],
["🏟️", "Stadium"],
["🗼", "Tokyo Tower"],
["🏯", "Japanese Castle"],
["🏚️", "Derelict House"],
["🏨", "Hotel"],
["🏭", "Factory"],
["🏘️", "Houses"],
["🏗️", "Building Construction"],
["💒", "Wedding"],
["🪵", "Wood"],
["🏥", "Hospital"],
["🏦", "Bank"],
["🗽", "Statue of Liberty"],
["🏢", "Office Building"],
["🏡", "House With Garden"],
["🪨", "Rock"],
["🧱", "Brick"],
["🏫", "School"],
["🏛️", "Classical Building"],
["🏰", "Castle"],
["🏠", "House"],
["🚟", "Suspension Railway"],
["🚠", "Mountain Cableway"],
["💺", "Seat"],
["🛩️", "Small Airplane"],
["🛰️", "Satellite"],
["🚡", "Aerial Tramway"],
["🛬", "Airplane Arrival"],
["🚁", "Helicopter"],
["🪂", "Parachute"],
["🛫", "Airplane Departure"],
["🛸", "Flying Saucer"],
["✈️", "Airplane"],
["🚀", "Rocket"],
["🛎️", "Bellhop Bell"],
["🧳", "Luggage"],
["⛴️", "Ferry"],
["🛳️", "Passenger Ship"],
["🛟", "Ring Buoy"],
["🛥️", "Motor Boat"],
["🚤", "Speedboat"],
["🛶", "Canoe"],
["⚓", "Anchor"],
["⛵", "Sailboat"],
["🚢", "Ship"],
["🦼", "Motorized Wheelchair"],
["🚝", "Monorail"],
["🦽", "Manual Wheelchair"],
["🚊", "Tram"],
["🚋", "Tram Car", "cable car"],
["🚈", "Light Rail"],
["🚎", "Trolleybus"],
["🚞", "Mountain Railway"],
["🚖", "Oncoming Taxi"],
["🛤️", "Railway Track"],
["🚏", "Bus Stop"],
["🚉", "Station"],
["🛴", "Kick Scooter"],
["🚃", "Railway Car"],
["🛺", "Auto Rickshaw"],
["🚄", "High-Speed Train"],
["🚍", "Oncoming Bus"],
["🚐", "Minibus"],
["🚅", "Bullet Train"],
["🛢️", "Oil Drum"],
["🛵", "Motor Scooter"],
["⛽", "Fuel Pump"],
["🛼", "Roller Skate"],
["🚆", "Train"],
["🛻", "Pickup Truck"],
["🚥", "Horizontal Traffic Light"],
["🚦", "Vertical Traffic Light"],
["🛹", "Skateboard"],
["🚛", "Articulated Lorry"],
["🚇", "Metro"],
["🚙", "Sport Utility Vehicle"],
["🚒", "Fire Engine"],
["🚲", "Bicycle"],
["🚔", "Oncoming Police Car"],
["🚕", "Taxi"],
["🛣️", "Motorway"],
["🚂", "Locomotive"],
["🚓", "Police Car"],
["🚜", "Tractor"],
["🚌", "Bus"],
["🏍️", "Motorcycle", "motorbike"],
["🚘", "Oncoming Automobile"],
["🚑", "Ambulance"],
["🚚", "Delivery Truck"],
["🛑", "Stop Sign"],
["🛞", "Wheel"],
["🚧", "Construction"],
["🏎️", "Racing Car"],
["🚗", "Automobile"],
["🚨", "Police Car Light"],
["💈", "Barber Pole"],
["⛲", "Fountain"],
["🌁", "Foggy"],
["🛝", "Playground Slide"],
["♨️", "Hot Springs"],
["🎠", "Carousel Horse"],
["⛺", "Tent"],
["🎡", "Ferris Wheel"],
["🎢", "Roller Coaster"],
["🏙️", "Cityscape"],
["🎪", "Circus Tent"],
["🌉", "Bridge at Night"],
["🌆", "Cityscape at Dusk"],
["🌇", "Sunset"],
["🌄", "Sunrise Over Mountains"],
["🌅", "Sunrise"],
["🌃", "Night With Stars"],
["🛘", "Landslide"],
["🗻", "Mount Fuji"],
["🏜️", "Desert"],
["🏕️", "Camping"],
["🏔️", "Snow-Capped Mountain"],
["🏞️", "National Park"],
["🌋", "Volcano"],
["🏝️", "Desert Island"],
["🏖️", "Beach With Umbrella"],
["⛰️", "Mountain"],
["🥉", "3rd Place Medal"],
["🥈", "2nd Place Medal"],
["🏅", "Sports Medal"],
["🎖️", "Military Medal"],
["🥇", "1st Place Medal"],
["🏆", "Trophy"],
["🪡", "Sewing Needle"],
["🧵", "Thread"],
["🧶", "Yarn"],
["🖼️", "Framed Picture"],
["🪢", "Knot"],
["🎨", "Artist Palette"],
["🎭", "Performing Arts"],
["🎑", "Moon Viewing Ceremony"],
["🎍", "Pine Decoration"],
["🎏", "Carp Streamer"],
["🎐", "Wind Chime"],
["🎎", "Japanese Dolls"],
["🎋", "Tanabata Tree"],
["🧨", "Firecracker"],
["🧧", "Red Envelope"],
["🎟️", "Admission Tickets"],
["🎫", "Ticket"],
["🎗️", "Reminder Ribbon"],
["🎇", "Sparkler"],
["🎃", "Jack-O-Lantern"],
["🎊", "Confetti Ball"],
["🎈", "Balloon"],
["🎆", "Fireworks"],
["🎁", "Wrapped Gift"],
["🎀", "Ribbon"],
["✨", "Sparkles"],
["🎄", "Christmas Tree"],
["🎉", "Party Popper"],
["🪀", "Yo-Yo"],
["🪆", "Nesting Dolls"],
["♟️", "Chess Pawn"],
["♣️", "Club Suit"],
["♦️", "Diamond Suit"],
["🎴", "Flower Playing Cards"],
["🪅", "Piñata"],
["♠️", "Spade Suit"],
["🎱", "Pool 8 Ball"],
["🀄", "Mahjong Red Dragon"],
["🕹️", "Joystick"],
["🧩", "Puzzle Piece"],
["🪁", "Kite"],
["🪩", "Mirror Ball"],
["🎰", "Slot Machine"],
["🃏", "Joker"],
["🔮", "Crystal Ball"],
["🪄", "Magic Wand"],
["🎲", "Game Die"],
["🎮", "Video Game"],
["🧸", "Teddy Bear"],
["♥️", "Heart Suit"],
["🎯", "Direct Hit"],
["🔫", "Pistol"],
["🏑", "Field Hockey"],
["🥍", "Lacrosse"],
["🥌", "Curling Stone"],
["🎽", "Running Shirt"],
["🏉", "Rugby Football"],
["🏸", "Badminton"],
["🥏", "Flying Disc"],
["🥅", "Goal Net"],
["🤿", "Diving Mask"],
["🥎", "Softball"],
["🎳", "Bowling"],
["🏒", "Ice Hockey"],
["🎿", "Skis"],
["🏓", "Ping Pong"],
["🏏", "Cricket Game"],
["⛸️", "Ice Skate"],
["⛳", "Flag In Hole"],
["🏐", "Volleyball"],
["🛷", "Sled"],
["🎾", "Tennis"],
["🥋", "Martial Arts Uniform"],
["⚾", "Baseball"],
["🎣", "Fishing Pole"],
["🥊", "Boxing Glove"],
["🏀", "Basketball"],
["⚽", "Soccer Ball"],
["🏈", "American Football"],
["✒️", "Black Nib"],
["🖋️", "Fountain Pen"],
["🖊️", "Pen"],
["🖌️", "Paintbrush"],
["🖍️", "Crayon"],
["✏️", "Pencil"],
["📝", "Memo"],
["🎚️", "Level Slider"],
["🎼", "Musical Score"],
["📻", "Radio"],
["🎛️", "Control Knobs"],
["🎙️", "Studio Microphone"],
["🎤", "Microphone"],
["🎧", "Headphone"],
["🎶", "Musical Notes"],
["🎵", "Musical Note"],
["👝", "Clutch Bag"],
["🥿", "Flat Shoe"],
["🩱", "One-Piece Swimsuit"],
["🪮", "Hair Pick"],
["👡", "Woman’s Sandal"],
["🥽", "Goggles"],
["⛑️", "Rescue Worker’s Helmet"],
["🩴", "Thong Sandal"],
["🩳", "Shorts"],
["👢", "Woman’s Boot"],
["👛", "Purse"],
["👘", "Kimono"],
["🥼", "Lab Coat"],
["👒", "Woman’s Hat"],
["🥻", "Sari"],
["🪭", "Folding Hand Fan"],
["👞", "Man’s Shoe"],
["👜", "Handbag"],
["🩲", "Briefs"],
["👖", "Jeans"],
["👚", "Woman’s Clothes"],
["🦺", "Safety Vest"],
["🧥", "Coat"],
["🧤", "Gloves"],
["🥾", "Hiking Boot"],
["📿", "Prayer Beads"],
["🧣", "Scarf"],
["🩰", "Ballet Shoes"],
["🧦", "Socks"],
["🧢", "Billed Cap"],
["👔", "Necktie"],
["👓", "Glasses"],
["🎒", "Backpack"],
["👗", "Dress"],
["👕", "T-Shirt"],
["🎩", "Top Hat"],
["👠", "High-heeled Shoe"],
["🪖", "Military Helmet"],
["👟", "Running Shoe"],
["🕶️", "Sunglasses"],
["👙", "Bikini"],
["💍", "Ring"],
["💄", "Lipstick"],
["🎓", "Graduation Cap"],
["🛍️", "Shopping Bags"],
["💎", "Gem Stone"],
["👑", "Crown"],
["🪊", "Trombone"],
["🪉", "Harp"],
["🪘", "Long Drum"],
["🪗", "Accordion"],
["🪕", "Banjo"],
["🪇", "Maracas"],
["🪈", "Flute"],
["🎻", "Violin"],
["🎷", "Saxophone"],
["🎺", "Trumpet"],
["🎹", "Musical Keyboard"],
["🥁", "Drum"],
["🎸", "Guitar"],
["⚱️", "Funeral Urn"],
["🪧", "Placard"],
["⚰️", "Coffin"],
["🪪", "Identification Card"],
["🪦", "Headstone"],
["🚬", "Cigarette"],
["🗿", "Moai", "moyai", "stone"],
["🪬", "Hamsa"],
["🧿", "Nazar Amulet"],
["🛗", "Elevator"],
["🪣", "Bucket"],
["🪠", "Plunger"],
["🪒", "Razor"],
["🧷", "Safety Pin"],
["🪤", "Mouse Trap"],
["🪥", "Toothbrush"],
["🧯", "Fire Extinguisher"],
["🧻", "Roll Of Paper"],
["🧽", "Sponge"],
["🪟", "Window"],
["🚽", "Toilet"],
["🪑", "Chair"],
["🛋️", "Couch and Lamp"],
["🛁", "Bathtub"],
["🧴", "Lotion Bottle"],
["🚿", "Shower"],
["🧺", "Basket"],
["🪞", "Mirror"],
["🚪", "Door"],
["🛏️", "Bed"],
["🧼", "Soap"],
["🧹", "Broom"],
["🛒", "Shopping Cart"],
["🫧", "Bubbles"],
["📠", "Fax Machine"],
["📟", "Pager"],
["☎️", "Telephone"],
["📲", "Mobile Phone With Arrow"],
["📞", "Telephone Receiver"],
["📱", "Mobile Phone"],
["📪", "Closed Mailbox With Lowered Flag"],
["📭", "Open Mailbox With Lowered Flag"],
["📫", "Closed Mailbox With Raised Flag"],
["📤", "Outbox Tray"],
["📮", "Postbox"],
["📨", "Incoming Envelope"],
["🗳️", "Ballot Box With Ballot"],
["📥", "Inbox Tray"],
["📬", "Open Mailbox With Raised Flag"],
["📩", "Envelope With Arrow"],
["✉️", "Envelope"],
["📦", "Package"],
["📧", "E-mail"],
["🗜️", "Clamp"],
["🦯", "White Cane"],
["🪛", "Screwdriver"],
["🪃", "Boomerang"],
["🪝", "Hook"],
["⛓️‍💥", "Broken Chain"],
["🔩", "Nut And Bolt"],
["🪜", "Ladder"],
["🧰", "Toolbox"],
["🧲", "Magnet"],
["🪚", "Carpentry Saw"],
["🪏", "Shovel"],
["⛏️", "Pick"],
["🪓", "Axe"],
["⚒️", "Hammer and Pick"],
["🔨", "Hammer"],
["🏹", "Bow And Arrow"],
["🔧", "Wrench"],
["🛠️", "Hammer And Wrench"],
["⚙️", "Gear"],
["🛡️", "Shield"],
["⚖️", "Balance Scale"],
["💣", "Bomb"],
["🗡️", "Dagger"],
["🔗", "Link"],
["⚔️", "Crossed Swords"],
["⛓️", "Chains"],
["🔏", "Locked With Pen"],
["🗝️", "Old Key"],
["🔓", "Unlocked"],
["🔐", "Locked With Key"],
["🔑", "Key"],
["🔒", "Locked"],
["🧫", "Petri Dish"],
["⚗️", "Alembic"],
["📡", "Satellite Antenna"],
["🔬", "Microscope"],
["🔭", "Telescope"],
["🧪", "Test Tube"],
["🧬", "DNA"],
["📼", "Videocassette"],
["🏮", "Red Paper Lantern"],
["🔦", "Flashlight"],
["📽️", "Film Projector"],
["🎞️", "Film Frames"],
["📹", "Video Camera"],
["📺", "Television"],
["🔍", "Magnifying Glass Tilted Left"],
["🎬", "Clapper Board"],
["🪔", "Diya Lamp"],
["🕯️", "Candle"],
["📸", "Camera With Flash"],
["📷", "Camera"],
["🎥", "Movie Camera"],
["🔎", "Magnifying Glass Tilted Right"],
["💡", "Light Bulb"],
["🪎", "Treasure Chest"],
["💴", "Yen Banknote"],
["💷", "Pound Banknote"],
["💶", "Euro Banknote"],
["💹", "Chart Increasing With Yen"],
["🧾", "Receipt"],
["💳", "Credit Card"],
["🪙", "Coin"],
["💵", "Dollar Banknote"],
["💸", "Money With Wings"],
["💰", "Money Bag"],
["🗄️", "File Cabinet"],
["📇", "Card Index"],
["🗃️", "Card File Box"],
["📏", "Straight Ruler"],
["📐", "Triangular Ruler"],
["📂", "Open File Folder"],
["🗂️", "Card Index Dividers"],
["📎", "Paperclip"],
["🗒️", "Spiral Notepad"],
["✂️", "Scissors"],
["🖇️", "Linked Paperclips"],
["📉", "Chart Decreasing"],
["📁", "File Folder"],
["🗑️", "Wastebasket"],
["📆", "Tear-Off Calendar"],
["📋", "Clipboard"],
["🗓️", "Spiral Calendar"],
["📊", "Bar Chart"],
["📌", "Pushpin"],
["💼", "Briefcase"],
["📅", "Calendar"],
["📈", "Chart Increasing"],
["📍", "Round Pushpin"],
["🖲️", "Trackball"],
["📀", "DVD"],
["🖨️", "Printer"],
["💽", "Computer Disk"],
["💾", "Floppy Disk"],
["🖱️", "Computer Mouse"],
["🔌", "Electric Plug"],
["⌨️", "Keyboard"],
["💿", "Optical Disk"],
["🧮", "Abacus"],
["🪫", "Low Battery"],
["🔋", "Battery"],
["🖥️", "Desktop Computer"],
["💻", "Laptop"],
["🗞️", "Rolled-Up Newspaper"],
["📒", "Ledger"],
["🔖", "Bookmark"],
["📑", "Bookmark Tabs"],
["📄", "Page Facing Up"],
["📙", "Orange Book"],
["📗", "Green Book"],
["📃", "Page With Curl"],
["📔", "Notebook With Decorative Cover"],
["📓", "Notebook"],
["📘", "Blue Book"],
["📰", "Newspaper"],
["📕", "Closed Book"],
["🏷️", "Label"],
["📜", "Scroll"],
["📖", "Open Book"],
["📚", "Books"],
["🩼", "Crutch"],
["🩹", "Adhesive Bandage"],
["🩻", "X-Ray"],
["💉", "Syringe"],
["🩺", "Stethoscope"],
["💊", "Pill"],
["🩸", "Drop Of Blood"],
["📯", "Postal Horn"],
["🔈", "Speaker Low Volume"],
["🔕", "Bell With Slash"],
["🔇", "Muted Speaker"],
["🔉", "Speaker Medium Volume"],
["🔊", "Speaker High Volume"],
["🔔", "Bell"],
["📣", "Megaphone"],
["📢", "Loudspeaker"],
["💱", "Currency Exchange"],
["💲", "Heavy Dollar Sign"],
["⚧️", "Transgender Symbol"],
["♂️", "Male Sign"],
["♀️", "Female Sign"],
["♒", "Aquarius"],
["♑", "Capricorn"],
["♍", "Virgo"],
["♈", "Aries"],
["♓", "Pisces"],
["♊", "Gemini"],
["♐", "Sagittarius"],
["⛎", "Ophiuchus"],
["♉", "Taurus"],
["♌", "Leo"],
["♏", "Scorpio"],
["♎", "Libra"],
["♋", "Cancer"],
["〰️", "Wavy Dash"],
["❕", "White Exclamation Mark"],
["❔", "White Question Mark"],
["⁉️", "Exclamation Question Mark"],
["❗", "Exclamation Mark"],
["❓", "Question Mark"],
["‼️", "Double Exclamation Mark"],
["🟰", "Heavy Equals Sign"],
["➗", "Divide"],
["➖", "Minus"],
["✖️", "Multiply"],
["♾️", "Infinity"],
["➕", "Plus"],
["☸️", "Wheel Of Dharma"],
["⚛️", "Atom Symbol"],
["🪯", "Khanda"],
["🔯", "Dotted Six-Pointed Star"],
["☯️", "Yin Yang"],
["☮️", "Peace Symbol"],
["☦️", "Orthodox Cross"],
["✡️", "Star Of David"],
["☪️", "Star And Crescent"],
["🕉️", "Om"],
["🕎", "Menorah"],
["✝️", "Latin Cross"],
["🛐", "Place Of Worship"],
["🫟", "Splatter"],
["📛", "Name Badge"],
["✳️", "Eight-Spoked Asterisk"],
["➿", "Double Curly Loop"],
["®️", "Registered"],
["™️", "Trade Mark"],
["©️", "Copyright"],
["〽️", "Part Alternation Mark"],
["✴️", "Eight-Pointed Star"],
["❇️", "Sparkle"],
["♻️", "Recycling Symbol"],
["🔰", "Japanese Symbol For Beginner"],
["❎", "Cross Mark Button"],
["⭕", "Hollow Red Circle"],
["☑️", "Check Box With Check"],
["🔱", "Trident Emblem"],
["⚜️", "Fleur-de-lis"],
["⚕️", "Medical Symbol"],
["➰", "Curly Loop"],
["❌", "Cross Mark"],
["✔️", "Check Mark"],
["✅", "Check Mark Button"],
["↙️", "Down-Left Arrow"],
["↖️", "Up-Left Arrow"],
["↘️", "Down-Right Arrow"],
["↗️", "Up-Right Arrow"],
["⤴️", "Right Arrow Curving Up"],
["🔚", "END Arrow"],
["↪️", "Left Arrow Curving Right"],
["↕️", "Up-Down Arrow"],
["↩️", "Right Arrow Curving Left"],
["🔃", "Clockwise Vertical Arrows"],
["⬅️", "Left Arrow"],
["🔙", "BACK Arrow"],
["🔛", "ON! Arrow"],
["⤵️", "Right Arrow Curving Down"],
["↔️", "Left-Right Arrow"],
["🔝", "TOP Arrow"],
["🔜", "SOON Arrow"],
["⬆️", "Up Arrow"],
["⬇️", "Down Arrow"],
["🔄", "Counterclockwise Arrows Button"],
["➡️", "Right Arrow"],
["🈷️", "Japanese “monthly Amount” Button"],
["🈁", "Japanese “here” Button"],
["🈶", "Japanese “not Free Of Charge” Button"],
["🈚", "Japanese “free Of Charge” Button"],
["🈂️", "Japanese “service Charge” Button"],
["🈴", "Japanese “passing Grade” Button"],
["🈸", "Japanese “application” Button"],
["🈹", "Japanese “discount” Button"],
["🔡", "Input Latin Lowercase"],
["🈳", "Japanese “vacancy” Button"],
["🉐", "Japanese “bargain” Button"],
["🈲", "Japanese “prohibited” Button"],
["㊗️", "Japanese “congratulations” Button"],
["🈯", "Japanese “reserved” Button"],
["🆎", "AB Button (Blood Type)"],
["🈺", "Japanese “open For Business” Button"],
["🆒", "COOL Button"],
["🅾️", "O Button (Blood Type)"],
["🈵", "Japanese “no Vacancy” Button"],
["🉑", "Japanese “acceptable” Button"],
["🆑", "CL Button"],
["🔣", "Input Symbols"],
["🆖", "NG Button"],
["🔠", "Input Latin Uppercase"],
["🆚", "VS Button"],
["🆗", "OK Button"],
["🆓", "FREE Button"],
["🔤", "Input Latin Letters"],
["㊙️", "Japanese “secret” Button"],
["🆙", "UP! Button"],
["🅱️", "B Button (Blood Type)"],
["🆔", "ID Button"],
["Ⓜ️", "Circled M"],
["🅰️", "A Button (Blood Type)"],
["🅿️", "P Button"],
["🆕", "NEW Button"],
["🆘", "SOS Button"],
["🔢", "Input Numbers"],
["ℹ️", "Information"],
["*️⃣", "Keycap: *"],
["#️⃣", "Keycap: #"],
["9️⃣", "Keycap: 9"],
["🔟", "Keycap: 10"],
["8️⃣", "Keycap: 8"],
["6️⃣", "Keycap: 6"],
["7️⃣", "Keycap: 7"],
["0️⃣", "Keycap: 0"],
["5️⃣", "Keycap: 5"],
["4️⃣", "Keycap: 4"],
["3️⃣", "Keycap: 3"],
["2️⃣", "Keycap: 2"],
["1️⃣", "Keycap: 1"],
["🛄", "Baggage Claim"],
["🛅", "Left Luggage"],
["🚾", "Water Closet"],
["🛃", "Customs"],
["🛂", "Passport Control"],
["🚹", "Men’s Room"],
["🚻", "Restroom"],
["♿", "Wheelchair Symbol"],
["🚮", "Litter In Bin Sign"],
["🏧", "ATM Sign"],
["🚺", "Women’s Room"],
["🚼", "Baby Symbol"],
["🚰", "Potable Water"],
["⏏️", "Eject Button"],
["⏮️", "Last Track Button"],
["⏪", "Fast Reverse Button"],
["⏬", "Fast Down Button"],
["◀️", "Reverse Button"],
["⏫", "Fast Up Button"],
["⏺️", "Record Button"],
["⏹️", "Stop Button"],
["🔽", "Downwards Button"],
["🔅", "Dim Button"],
["🔂", "Repeat Single Button"],
["🔼", "Upwards Button"],
["🔀", "Shuffle Tracks Button"],
["📳", "Vibration Mode"],
["⏯️", "Play Or Pause Button"],
["📴", "Mobile Phone Off"],
["⏭️", "Next Track Button"],
["⏩", "Fast-Forward Button"],
["📶", "Antenna Bars"],
["⏸️", "Pause Button"],
["🔆", "Bright Button"],
["🛜", "Wireless"],
["🎦", "Cinema"],
["🔁", "Repeat Button"],
["▶️", "Play Button"],
["🚳", "No Bicycles"],
["🚱", "Non-Potable Water"],
["🚯", "No Littering"],
["🚷", "No Pedestrians"],
["🚸", "Children Crossing"],
["🚭", "No Smoking"],
["📵", "No Mobile Phones"],
["☣️", "Biohazard"],
["☢️", "Radioactive"],
["⛔", "No Entry"],
["🚫", "Prohibited"],
["🔞", "No One Under Eighteen"],
["⚠️", "Warning"],
["◽", "White Medium-Small Square"],
["◼️", "Black Medium Square"],
["◻️", "White Medium Square"],
["▫️", "White Small Square"],
["◾", "Black Medium-Small Square"],
["🔳", "White Square Button"],
["🔸", "Small Orange Diamond"],
["▪️", "Black Small Square"],
["🔶", "Large Orange Diamond"],
["🔲", "Black Square Button"],
["🔘", "Radio Button"],
["🔹", "Small Blue Diamond"],
["🟤", "Brown Circle"],
["🟧", "Orange Square"],
["⬜", "White Large Square"],
["🟫", "Brown Square"],
["🟨", "Yellow Square"],
["🟪", "Purple Square"],
["🔻", "Red Triangle Pointed Down"],
["🔷", "Large Blue Diamond"],
["🔺", "Red Triangle Pointed Up"],
["⬛", "Black Large Square"],
["🟦", "Blue Square"],
["🟩", "Green Square"],
["🟣", "Purple Circle"],
["💠", "Diamond With A Dot"],
["🟠", "Orange Circle"],
["🟥", "Red Square"],
["⚪", "White Circle"],
["⚫", "Black Circle"],
["🟡", "Yellow Circle"],
["🔵", "Blue Circle"],
["🔴", "Red Circle"],
["🟢", "Green Circle"],
["🏴󠁧󠁢󠁷󠁬󠁳󠁿", "Flag: Wales"],
["🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Flag: Scotland"],
["🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Flag: England"],
["🇨🇶", "Flag: Sark"],
["🇵🇳", "Flag: Pitcairn Islands"],
["🇸🇧", "Flag: Solomon Islands"],
["🇸🇹", "Flag: São Tomé &amp; Príncipe"],
["🇩🇯", "Flag: Djibouti"],
["🇬🇲", "Flag: Gambia"],
["🇲🇸", "Flag: Montserrat"],
["🇸🇲", "Flag: San Marino"],
["🇫🇰", "Flag: Falkland Islands"],
["🇬🇦", "Flag: Gabon"],
["🇰🇾", "Flag: Cayman Islands"],
["🇬🇶", "Flag: Equatorial Guinea"],
["🇬🇼", "Flag: Guinea-Bissau"],
["🇸🇯", "Flag: Svalbard &amp; Jan Mayen"],
["🇬🇸", "Flag: South Georgia &amp; South Sandwich Islands"],
["🇰🇲", "Flag: Comoros"],
["🇳🇷", "Flag: Nauru"],
["🇱🇸", "Flag: Lesotho"],
["🇨🇫", "Flag: Central African Republic"],
["🇲🇼", "Flag: Malawi"],
["🇻🇺", "Flag: Vanuatu"],
["🇰🇮", "Flag: Kiribati"],
["🇹🇬", "Flag: Togo"],
["🇵🇫", "Flag: French Polynesia"],
["🇳🇦", "Flag: Namibia"],
["🇹🇻", "Flag: Tuvalu"],
["🇧🇮", "Flag: Burundi"],
["🇱🇮", "Flag: Liechtenstein"],
["🇹🇱", "Flag: Timor-Leste"],
["🇹🇲", "Flag: Turkmenistan"],
["🇳🇫", "Flag: Norfolk Island"],
["🇷🇼", "Flag: Rwanda"],
["🇲🇭", "Flag: Marshall Islands"],
["🇰🇳", "Flag: St. Kitts &amp; Nevis"],
["🇬🇮", "Flag: Gibraltar"],
["🇨🇬", "Flag: Congo - Brazzaville"],
["🇹🇰", "Flag: Tokelau"],
["🇵🇾", "Flag: Paraguay"],
["🇸🇭", "Flag: St. Helena"],
["🇹🇨", "Flag: Turks &amp; Caicos Islands"],
["🇲🇵", "Flag: Northern Mariana Islands"],
["🇸🇸", "Flag: South Sudan"],
["🇨🇻", "Flag: Cape Verde"],
["🇸🇿", "Flag: Eswatini"],
["🇹🇯", "Flag: Tajikistan"],
["🇲🇿", "Flag: Mozambique"],
["🇳🇨", "Flag: New Caledonia"],
["🇬🇳", "Flag: Guinea"],
["🇹🇦", "Flag: Tristan Da Cunha"],
["🇸🇨", "Flag: Seychelles"],
["🇵🇼", "Flag: Palau"],
["🇧🇻", "Flag: Bouvet Island"],
["🇪🇷", "Flag: Eritrea"],
["🇧🇯", "Flag: Benin"],
["🇸🇱", "Flag: Sierra Leone"],
["🇫🇴", "Flag: Faroe Islands"],
["🇬🇫", "Flag: French Guiana"],
["🇩🇲", "Flag: Dominica"],
["🇬🇺", "Flag: Guam"],
["🇭🇲", "Flag: Heard &amp; Mcdonald Islands"],
["🇻🇬", "Flag: British Virgin Islands"],
["🇨🇰", "Flag: Cook Islands"],
["🇬🇩", "Flag: Grenada"],
["🇳🇺", "Flag: Niue"],
["🇲🇻", "Flag: Maldives"],
["🇩🇬", "Flag: Diego Garcia"],
["🇦🇼", "Flag: Aruba"],
["🇨🇮", "Flag: Côte D’Ivoire"],
["🇾🇹", "Flag: Mayotte"],
["🇲🇷", "Flag: Mauritania"],
["🇺🇬", "Flag: Uganda"],
["🇨🇲", "Flag: Cameroon"],
["🇬🇱", "Flag: Greenland"],
["🇱🇨", "Flag: St. Lucia"],
["🇫🇲", "Flag: Micronesia"],
["🇮🇴", "Flag: British Indian Ocean Territory"],
["🇦🇮", "Flag: Anguilla"],
["🇲🇬", "Flag: Madagascar"],
["🇧🇳", "Flag: Brunei"],
["🇻🇨", "Flag: St. Vincent &amp; Grenadines"],
["🇰🇬", "Flag: Kyrgyzstan"],
["🇲🇱", "Flag: Mali"],
["🇧🇼", "Flag: Botswana"],
["🇹🇿", "Flag: Tanzania"],
["🇧🇱", "Flag: St. Barthélemy"],
["🇦🇬", "Flag: Antigua &amp; Barbuda"],
["🇧🇫", "Flag: Burkina Faso"],
["🇲🇺", "Flag: Mauritius"],
["🇿🇲", "Flag: Zambia"],
["🇵🇲", "Flag: St. Pierre &amp; Miquelon"],
["🇨🇵", "Flag: Clipperton Island"],
["🇬🇵", "Flag: Guadeloupe"],
["🇧🇲", "Flag: Bermuda"],
["🇰🇼", "Flag: Kuwait"],
["🇧🇹", "Flag: Bhutan"],
["🇬🇬", "Flag: Guernsey"],
["🇦🇩", "Flag: Andorra"],
["🇹🇫", "Flag: French Southern Territories"],
["🇻🇮", "Flag: U.S. Virgin Islands"],
["🇧🇭", "Flag: Bahrain"],
["🇸🇷", "Flag: Suriname"],
["🇲🇰", "Flag: North Macedonia"],
["🇦🇽", "Flag: Åland Islands"],
["🇧🇿", "Flag: Belize"],
["🇨🇨", "Flag: Cocos (Keeling) Islands"],
["🇱🇺", "Flag: Luxembourg"],
["🇨🇾", "Flag: Cyprus"],
["🇪🇭", "Flag: Western Sahara"],
["🇹🇴", "Flag: Tonga"],
["🇱🇰", "Flag: Sri Lanka"],
["🇷🇪", "Flag: Réunion"],
["🇦🇴", "Flag: Angola"],
["🇳🇮", "Flag: Nicaragua"],
["🇯🇪", "Flag: Jersey"],
["🇨🇼", "Flag: Curaçao"],
["🇧🇶", "Flag: Caribbean Netherlands"],
["🇲🇩", "Flag: Moldova"],
["🇸🇳", "Flag: Senegal"],
["🇲🇳", "Flag: Mongolia"],
["🇱🇾", "Flag: Libya"],
["🇫🇯", "Flag: Fiji"],
["🇨🇩", "Flag: Congo - Kinshasa"],
["🇸🇮", "Flag: Slovenia"],
["🇦🇶", "Flag: Antarctica"],
["🇱🇷", "Flag: Liberia"],
["🇼🇸", "Flag: Samoa"],
["🇧🇸", "Flag: Bahamas"],
["🇲🇲", "Flag: Myanmar (Burma)"],
["🇲🇶", "Flag: Martinique"],
["🇿🇼", "Flag: Zimbabwe"],
["🇱🇦", "Flag: Laos"],
["🇺🇾", "Flag: Uruguay"],
["🇧🇧", "Flag: Barbados"],
["🇸🇩", "Flag: Sudan"],
["🇸🇽", "Flag: Sint Maarten"],
["🇦🇸", "Flag: American Samoa"],
["🇸🇴", "Flag: Somalia"],
["🇹🇳", "Flag: Tunisia"],
["🇹🇩", "Flag: Chad"],
["🇲🇫", "Flag: St. Martin"],
["🇲🇪", "Flag: Montenegro"],
["🇺🇿", "Flag: Uzbekistan"],
["🇬🇾", "Flag: Guyana"],
["🇲🇨", "Flag: Monaco"],
["🇧🇾", "Flag: Belarus"],
["🇵🇬", "Flag: Papua New Guinea"],
["🇼🇫", "Flag: Wallis &amp; Futuna"],
["🇺🇳", "Flag: United Nations"],
["🇮🇲", "Flag: Isle Of Man"],
["🇴🇲", "Flag: Oman"],
["🇧🇦", "Flag: Bosnia &amp; Herzegovina"],
["🇨🇺", "Flag: Cuba"],
["🇲🇹", "Flag: Malta"],
["🇽🇰", "Flag: Kosovo"],
["🇳🇪", "Flag: Niger"],
["🇵🇦", "Flag: Panama"],
["🇨🇷", "Flag: Costa Rica"],
["🇪🇨", "Flag: Ecuador"],
["🇱🇻", "Flag: Latvia"],
["🇪🇹", "Flag: Ethiopia"],
["🇬🇭", "Flag: Ghana"],
["🇾🇪", "Flag: Yemen"],
["🇭🇳", "Flag: Honduras"],
["🇻🇪", "Flag: Venezuela"],
["🇮🇨", "Flag: Canary Islands"],
["🇦🇫", "Flag: Afghanistan"],
["🇰🇿", "Flag: Kazakhstan"],
["🇸🇻", "Flag: El Salvador"],
["🇦🇨", "Flag: Ascension Island"],
["🇭🇷", "Flag: Croatia"],
["🇭🇹", "Flag: Haiti"],
["🇯🇴", "Flag: Jordan"],
["🇦🇿", "Flag: Azerbaijan"],
["🇰🇪", "Flag: Kenya"],
["🇨🇽", "Flag: Christmas Island"],
["🇧🇴", "Flag: Bolivia"],
["🇨🇿", "Flag: Czechia"],
["🇻🇦", "Flag: Vatican City"],
["🇪🇦", "Flag: Ceuta &amp; Melilla"],
["🇶🇦", "Flag: Qatar"],
["🇨🇱", "Flag: Chile"],
["🇰🇭", "Flag: Cambodia"],
["🇬🇪", "Flag: Georgia"],
["🇬🇹", "Flag: Guatemala"],
["🇸🇰", "Flag: Slovakia"],
["🇮🇷", "Flag: Iran"],
["🇩🇴", "Flag: Dominican Republic"],
["🇮🇸", "Flag: Iceland"],
["🇹🇹", "Flag: Trinidad &amp; Tobago"],
["🇧🇩", "Flag: Bangladesh"],
["🇦🇲", "Flag: Armenia"],
["🇦🇹", "Flag: Austria"],
["🇲🇴", "Flag: Macao Sar China"],
["🇮🇶", "Flag: Iraq"],
["🇩🇿", "Flag: Algeria"],
["🇱🇹", "Flag: Lithuania"],
["🇰🇵", "Flag: North Korea"],
["🇳🇴", "Flag: Norway"],
["🇵🇪", "Flag: Peru"],
["🇪🇪", "Flag: Estonia"],
["🇫🇮", "Flag: Finland"],
["🇷🇸", "Flag: Serbia"],
["🇧🇬", "Flag: Bulgaria"],
["🇭🇰", "Flag: Hong Kong Sar China"],
["🇳🇵", "Flag: Nepal"],
["🇸🇾", "Flag: Syria"],
["🇯🇲", "Flag: Jamaica"],
["🇿🇦", "Flag: South Africa"],
["🇺🇲", "Flag: U.S. Outlying Islands"],
["🇳🇿", "Flag: New Zealand"],
["🇸🇪", "Flag: Sweden"],
["🇪🇬", "Flag: Egypt"],
["🇵🇸", "Flag: Palestinian Territories"],
["🇳🇬", "Flag: Nigeria"],
["🇦🇪", "Flag: United Arab Emirates"],
["🇩🇰", "Flag: Denmark"],
["🇦🇷", "Flag: Argentina"],
["🇱🇧", "Flag: Lebanon"],
["🇧🇪", "Flag: Belgium"],
["🇬🇷", "Flag: Greece"],
["🇷🇴", "Flag: Romania"],
["🇵🇭", "Flag: Philippines"],
["🇪🇺", "Flag: European Union"],
["🇭🇺", "Flag: Hungary"],
["🇦🇱", "Flag: Albania"],
["🇵🇷", "Flag: Puerto Rico"],
["🇸🇦", "Flag: Saudi Arabia"],
["🇨🇭", "Flag: Switzerland"],
["🇲🇦", "Flag: Morocco"],
["🇮🇩", "Flag: Indonesia"],
["🇨🇴", "Flag: Colombia"],
["🇵🇹", "Flag: Portugal"],
["🇮🇱", "Flag: Israel"],
["🇵🇰", "Flag: Pakistan"],
["🇺🇦", "Flag: Ukraine"],
["🇸🇬", "Flag: Singapore"],
["🇰🇷", "Flag: South Korea"],
["🇹🇭", "Flag: Thailand"],
["🇷🇺", "Flag: Russia"],
["🇩🇪", "Flag: Germany"],
["🇮🇪", "Flag: Ireland"],
["🇵🇱", "Flag: Poland"],
["🇦🇺", "Flag: Australia"],
["🇪🇸", "Flag: Spain"],
["🇲🇾", "Flag: Malaysia"],
["🇻🇳", "Flag: Vietnam"],
["🇫🇷", "Flag: France"],
["🇹🇷", "Flag: Turkey"],
["🇧🇷", "Flag: Brazil"],
["🇲🇽", "Flag: Mexico"],
["🇬🇧", "Flag: United Kingdom"],
["🇮🇹", "Flag: Italy"],
["🇨🇳", "Flag: China"],
["🇯🇵", "Flag: Japan"],
["🇳🇱", "Flag: Netherlands"],
["🇹🇼", "Flag: Taiwan"],
["🇮🇳", "Flag: India"],
["🇨🇦", "Flag: Canada"],
["🇺🇸", "Flag: United States"],
["🏳️", "White Flag"],
["🎌", "Crossed Flags"],
["🏴", "Black Flag"],
["🏳️‍⚧️", "Transgender Flag"],
["🏴‍☠️", "Pirate Flag"],
["🏳️‍🌈", "Rainbow Flag"],
["🏁", "Chequered Flag"],
["🚩", "Triangular Flag"],
]

export function getEmojiSuggestions(alias) {
    let suggestions = [];
    let start = performance.now();
    for (let emoji of EMOJIS) {
        for (let i = 1; i < emoji.length; i++) {
            if (emoji[i].toLowerCase().includes(alias)) {
                suggestions.push(emoji[0])
                break;
            }
        }
    }
    let elapsed = performance.now() - start;
    console.log("Received suggestions in", elapsed, "ms")
    return suggestions;
}

window.getEmojiSuggestions = getEmojiSuggestions